---
# tasks file for kerberos

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: kerberos

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: kerberos

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: kerberos

- name: Create Kerberos configuration file
  template: >
    src=krb5.conf.j2
    dest=/etc/krb5.conf
    owner=root
    group=root
    mode=0644
  tags: kerberos
